### ISSUE TITLE
Injecting the options

### ISSUE THREAD

**Issue by zoomclub** [pilwon/react-famous#10]
In looking at the different samples I see that surface and modifier options are always hardwired into the components. This is okay for the demos, still I'm a great fan of JSON and it would be nice to have a system where options can be specified in JSON and then injected into a react-famous app. This would to supply a set of currently active options and allow the set of options to be exchangeable as well.

It looks like the react-radium project is using a similar approach with injecting styles. Maybe there is a way to just use react-radium for options as well?

**Comment by pilwon** [comment]
@zoomclub It expects `options` [prop as just JS object](https://github.com/pilwon/react-famous/blob/fcaed2a34c51d30dd0598017c57648d4a5a72b7c/src/lib/FamousMixin.js#L15) so you can [build an object and pass it as prop](https://github.com/pilwon/react-famous/blob/fcaed2a34c51d30dd0598017c57648d4a5a72b7c/examples/components/test/Seed/App.jsx#L67-L76) or load it from an external file (JSON or transpiled from YAML, INI, TOML, etc.), local storage, remote server, or others, however you like.

To load JSON with `webpack`, you can `npm install json-loader`, add `{test: /\.json$/, loaders: 'json'}` to `module.loaders` array of your webpack config file, then import any JSON file using `require('./foo.json')`. You can then pass this JS object imported from JSON file to one of the `props.options`.

**Comment by zoomclub** [comment]
Good to know, thanks for the clarification. Firebase seems like the right fit for me, being an immutable state source that can swap documents and place refs/cursors where they are desired.
