### ISSUE TITLE
View not working?

### ISSUE THREAD

**Issue by swennemans** [pilwon/react-famous#11]
I'm trying to create view that has a number of nested children, however when creating a view it doesn't get rendered. 

This works fine:

```
<Surface> 
  <h1>Hello world</h1>
</Surface>
```

This doesn't:

```
<View>
  <Surface> 
    <h1>Hello world</h1>
  </Surface>
</View>
```

When I look into the chrome elements tab, I see the following tag `<noscript data-reactid=".0.0.$0.0"></noscript>` instead of (what I would expect) `<div data-famous="View" data-reactid=".0.0.$0.0"></div>`

Should I specify specific option when initiating a View? I've tried to set size etc. with no luck.

**Comment by pilwon** [comment]
@swennemans It works fine for me. You don't need to set any option to get it rendered. Did you forget to wrap your code with `<Context>...</Context>`?

**Comment by pilwon** [comment]
Also check ensure you are not importing `famous` instead of `react-famous` module. (ex: `famous/core/View` instead of `react-famous/core/View`)

**Comment by swennemans** [comment]
@pilwon Thanks for your fast reply. The problem was, like you suggested, that I imported famous instead of react-famous, rookie mistake. 
It's working now, awesome! I really enjoy working with this library it's the best of both worlds :+1: Thanks for making this.
