### ISSUE TITLE
Browserify error: Cannot find module 'lodash/object/defaults'

### ISSUE THREAD

**Issue by ghost** [pilwon/react-famous#12]
Hello,

Really liking the demo! Never actually did stuff with famous, but can't wait to get started. 

I added installed react-famous with node, and now I'm trying to browserify it. 

And I get the following error: 

```
Timons-MacBook-Pro:www timon$ sudo browserify index.js -o bundle.js`
Error: Cannot find module 'lodash/object/defaults' from '/Users/timon/Teamzy/www/node_modules/react-famous/core'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

Got any idea what might be causing this?

**Comment by pilwon** [comment]
@txixyo As the error message says, it's not resolving `lodash/object/defaults`. Try fixing the module search path.

**Comment by ghost** [comment]
Derp. Kinda newish to node. Figured it out. Also had to do `npm install lodash` . I somehow expected all modules to be installed when I installed react-famous.

Thanks for the quick reply!

**Comment by pilwon** [comment]
@txixyo That happens. If you still have an issue, try running https://github.com/pilwon/react-famous-seed then swap in browserify for customization.
