### ISSUE TITLE
Eventing with React-Famous

### ISSUE THREAD

**Issue by cj3kim** [pilwon/react-famous#13]
Hi @pilwon

I am heavily considering using your framework. I am curious about how event handling and piping is done in the react-famous way because I frequently pipe events from one view to another. 

For example, if I have a view/react-famous component that has an active input/output, how do I pipe events from one react-famous component to another? Has this functionality been built already? If it has, do you have an example?

**Comment by pilwon** [comment]
@cj3kim There's no sugar like `fa-pipe-from`/`fa-pipe-to` (of `famous-angular`) in `react-famous`. The common pattern is you access raw famo.us instances in `componentDidMount()` by calling [.getFamous()](https://github.com/pilwon/react-famous/search?utf8=%E2%9C%93&q=getFamous) on `refs` then do anything you want with it including event piping. You can find piping examples [here](https://github.com/pilwon/react-famous/search?utf8=%E2%9C%93&q=pipe&type=Code). For inter-component piping, we don't have code example yet but it should be achieved by passing a famo.us instance getter function via `props` and passing it down the component tree, just like how inter-component communication works in React.

**Comment by cj3kim** [comment]
Thanks! I will look into it.
